---
title: "Introduction"
author: "Kushal K Dey"
date: "1/19/2017"
output: html_document
---

## Introduction

Logo plots are a popular tool in bioinformatics and regulatory genomics studies for representing sequence alignment patterns and for sequence and protein motif detection. One of the first and widely used logo plotting tools is **seqLogo** by Oliver Bembom [Bembom2016], specifically targeted at DNA sequence alignment. However, it has a library of only 4 symbols - A, C, G and T- corresponding to the 4 nucleotides. The package **RWebLogo** is an extension of WebLogo python package that plots custom sequence logos by extending it to all alphabets. Another package **motifStack** works with both DNA/RNA sequence motif and amino acid sequence motif and customizes font size and colors.

**Logolas** adds more flexibility by customizing logos and the graphical design of the logo plots. Also it extends the library of symbols beyond English alphabets to numbers, symbols (arrows, punctuations) and to alphanumeric strings. It allows the user to choose a range of information criteria to determine logo sizes. It provides a simple user interface to create new logos and add them to their personalized library of logos and even apply them in strings. We show several applications in genomics, ecology and document mining, where such logo plots can be applied.

